const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

const VEHICLE_TYPES = {
  MOTORCYCLE: 'MOTORCYCLE',
  CAR: 'CAR',
  COMMERCIAL: 'COMMERCIAL',
};

const SESSION_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  EMERGENCY: 'EMERGENCY',
};

const SENSOR_TYPES = {
  GPS: 'GPS',
  CAMERA: 'CAMERA',
  ACCELEROMETER: 'ACCELEROMETER',
  GYROSCOPE: 'GYROSCOPE',
  HELMET: 'HELMET',
  SEATBELT: 'SEATBELT',
  ALCOHOL: 'ALCOHOL',
  EYE: 'EYE',
  RAIN: 'RAIN',
  ULTRASONIC: 'ULTRASONIC',
};

const SENSOR_STATUS = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
};

const DRIVING_EVENT_TYPES = {
  HELMET_VERIFIED: 'HELMET_VERIFIED',
  SEATBELT_VERIFIED: 'SEATBELT_VERIFIED',
  SAFE_SPEED: 'SAFE_SPEED',
  PHONE_DETECTED: 'PHONE_DETECTED',
  OVERSPEED: 'OVERSPEED',
  SAFE_BRAKING: 'SAFE_BRAKING',
  HARSH_BRAKING: 'HARSH_BRAKING',
  DROWSINESS: 'DROWSINESS',
  RASH_DRIVING: 'RASH_DRIVING',
  SIGNAL_COMPLIANCE: 'SIGNAL_COMPLIANCE',
  WRONG_SIDE: 'WRONG_SIDE',
  EMERGENCY: 'EMERGENCY',
  ALCOHOL_DETECTED: 'ALCOHOL_DETECTED',
  LANE_DEPARTURE: 'LANE_DEPARTURE',
};

const VIOLATION_TYPES = {
  NO_HELMET: 'NO_HELMET',
  NO_SEATBELT: 'NO_SEATBELT',
  PHONE_USAGE: 'PHONE_USAGE',
  OVERSPEED: 'OVERSPEED',
  WRONG_SIDE: 'WRONG_SIDE',
  SIGNAL_JUMP: 'SIGNAL_JUMP',
  RASH_DRIVING: 'RASH_DRIVING',
  DRINK_DRIVING: 'DRINK_DRIVING',
  DROWSINESS: 'DROWSINESS',
  HARSH_BRAKING: 'HARSH_BRAKING',
  LANE_DEPARTURE: 'LANE_DEPARTURE',
  ALCOHOL_DETECTED: 'ALCOHOL_DETECTED',
};

const VIOLATION_PENALTIES = {
  [VIOLATION_TYPES.NO_HELMET]: { points: 50, score: 50 },
  [VIOLATION_TYPES.NO_SEATBELT]: { points: 50, score: 50 },
  [VIOLATION_TYPES.PHONE_USAGE]: { points: 100, score: 100 },
  [VIOLATION_TYPES.OVERSPEED]: { points: 100, score: 100 },
  [VIOLATION_TYPES.WRONG_SIDE]: { points: 150, score: 150 },
  [VIOLATION_TYPES.SIGNAL_JUMP]: { points: 200, score: 200 },
  [VIOLATION_TYPES.RASH_DRIVING]: { points: 150, score: 150 },
  [VIOLATION_TYPES.DRINK_DRIVING]: { points: 500, score: 500 },
  [VIOLATION_TYPES.DROWSINESS]: { points: 100, score: 100 },
  [VIOLATION_TYPES.HARSH_BRAKING]: { points: 30, score: 30 },
  [VIOLATION_TYPES.LANE_DEPARTURE]: { points: 50, score: 50 },
  [VIOLATION_TYPES.ALCOHOL_DETECTED]: { points: 500, score: 500 },
};

const SAFE_BEHAVIOR_REWARDS = {
  HELMET_COMPLIANCE: { points: 10, score: 10 },
  SEATBELT_COMPLIANCE: { points: 10, score: 10 },
  SPEED_COMPLIANCE: { points: 15, score: 15 },
  NO_PHONE_USAGE: { points: 20, score: 20 },
  SMOOTH_DRIVING: { points: 20, score: 20 },
  SAFE_BRAKING: { points: 15, score: 15 },
  TRAFFIC_SIGNAL_COMPLIANCE: { points: 15, score: 15 },
  SAFE_DISTANCE: { points: 25, score: 25 },
  DAILY_CHALLENGE: { points: 50, score: 50 },
  WEEKLY_SAFE_DRIVER: { points: 100, score: 100 },
};

const ALERT_TYPES = {
  SPEED_WARNING: 'SPEED_WARNING',
  OVERSPEED: 'OVERSPEED',
  PHONE_DETECTED: 'PHONE_DETECTED',
  NO_HELMET: 'NO_HELMET',
  NO_SEATBELT: 'NO_SEATBELT',
  HARSH_BRAKING: 'HARSH_BRAKING',
  DROWSINESS: 'DROWSINESS',
  RASH_DRIVING: 'RASH_DRIVING',
  WRONG_SIDE: 'WRONG_SIDE',
  SIGNAL_JUMP: 'SIGNAL_JUMP',
  ALCOHOL_DETECTED: 'ALCOHOL_DETECTED',
  EMERGENCY: 'EMERGENCY',
  HELMET_REMINDER: 'HELMET_REMINDER',
  SEATBELT_REMINDER: 'SEATBELT_REMINDER',
  SAFE_DRIVING: 'SAFE_DRIVING',
  POINTS_EARNED: 'POINTS_EARNED',
  REWARD_AVAILABLE: 'REWARD_AVAILABLE',
  ACHIEVEMENT_UNLOCKED: 'ACHIEVEMENT_UNLOCKED',
};

const ALERT_SEVERITY = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
};

const REWARD_CATEGORIES = {
  FOOD: 'FOOD',
  FUEL: 'FUEL',
  SHOPPING: 'SHOPPING',
  SERVICE: 'SERVICE',
  INSURANCE: 'INSURANCE',
  OTHER: 'OTHER',
};

const REDEMPTION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
};

const EMERGENCY_TRIGGER_TYPES = {
  MANUAL_SOS: 'MANUAL_SOS',
  CRASH_DETECTED: 'CRASH_DETECTED',
  HARSH_IMPACT: 'HARSH_IMPACT',
  DROWSINESS_CRITICAL: 'DROWSINESS_CRITICAL',
};

const EMERGENCY_STATUS = {
  TRIGGERED: 'TRIGGERED',
  CONTACTED: 'CONTACTED',
  RESOLVED: 'RESOLVED',
};

const LEADERBOARD_PERIODS = {
  WEEKLY: 'weekly',
  MONTHLY: 'monthly',
  ALL_TIME: 'all-time',
};

const INITIAL_SAFETY_SCORE = 85;
const MIN_SAFETY_SCORE = 0;
const MAX_SAFETY_SCORE = 100;

const SOCKET_EVENTS = {
  DRIVER_JOIN: 'driver:join',
  DRIVER_LEAVE: 'driver:leave',
  SENSOR_UPDATE: 'sensor:update',
  SPEED_UPDATE: 'speed:update',
  SAFETY_UPDATE: 'safety:update',
  ALERT_NEW: 'alert:new',
  VIOLATION_NEW: 'violation:new',
  SCORE_UPDATE: 'score:update',
  POINTS_UPDATE: 'points:update',
  DRIVING_START: 'driving:start',
  DRIVING_END: 'driving:end',
  EMERGENCY_TRIGGER: 'emergency:trigger',
};

const DEMO_STAGES = {
  STAGE_1: 'STAGE_1',
  STAGE_2: 'STAGE_2',
  STAGE_3: 'STAGE_3',
  STAGE_4: 'STAGE_4',
  STAGE_5: 'STAGE_5',
};

const SIMULATION_MODES = {
  SAFE: 'safe',
  WARNING: 'warning',
  VIOLATION: 'violation',
  EMERGENCY: 'emergency',
};

const DEVICE_TYPES = {
  ESP32: 'ESP32',
  RASPBERRY_PI: 'RASPBERRY_PI',
  ARDUINO: 'ARDUINO',
  MOBILE_APP: 'MOBILE_APP',
  OTHER: 'OTHER',
};

module.exports = {
  USER_ROLES,
  VEHICLE_TYPES,
  SESSION_STATUS,
  SENSOR_TYPES,
  SENSOR_STATUS,
  DRIVING_EVENT_TYPES,
  VIOLATION_TYPES,
  VIOLATION_PENALTIES,
  SAFE_BEHAVIOR_REWARDS,
  ALERT_TYPES,
  ALERT_SEVERITY,
  REWARD_CATEGORIES,
  REDEMPTION_STATUS,
  EMERGENCY_TRIGGER_TYPES,
  EMERGENCY_STATUS,
  LEADERBOARD_PERIODS,
  INITIAL_SAFETY_SCORE,
  MIN_SAFETY_SCORE,
  MAX_SAFETY_SCORE,
  SOCKET_EVENTS,
  DEMO_STAGES,
  SIMULATION_MODES,
  DEVICE_TYPES,
};